### ISSUE TITLE
Implement Utility ID 0x4

### ISSUE THREAD

**Issue by InternalLoss** [PretendoNetwork/mario-kart-7#1]
When a copy of Mario Kart 7 connects for the first time, `Unsupported Utility method ID: 0x4` appears on the server and it doesn't progress. I've attached a copy of three 3DSes connecting to MK7 for the first time (lmao) to try and implement this.

[Three3DSes_MK7_OhMy.pcapng.gz](https://github.com/PretendoNetwork/mk7-secure/files/7341481/Three3DSes_MK7_OhMy.pcapng.gz)

**Comment by DaniElectra** [comment]
This issue can be closed

**Comment by InternalLoss** [comment]
Closing.
